Updated docker scripts from moodlehq, made changes to run with Apple M1 CPU, updated to run PHP 7.4 by default

diff --git a/bin/moodle-docker-compose b/bin/moodle-docker-compose
--- a/bin/moodle-docker-compose
+++ b/bin/moodle-docker-compose
@@ -24,12 +24,19 @@ done
 basedir="$( cd -P "$( dirname "$SOURCE" )/../" && pwd )"
 export ASSETDIR="${basedir}/assets"
 
-
-dockercompose="docker-compose -f ${basedir}/base.yml"
+# Test if we have docker compose v2, and keep quiet if we don't.
+ver=$(docker compose version > /dev/null 2>&1 && docker compose version --short) || true
+if [[ $ver =~ ^v?2 ]]; then
+  dockercompose="docker compose"
+else
+  echo 'Compose v2 is not available in Docker CLI, falling back to use docker-compose script'
+  dockercompose="docker-compose"
+fi
+dockercompose="${dockercompose} -f ${basedir}/base.yml"
 dockercompose="${dockercompose} -f ${basedir}/service.mail.yml"
 
 # PHP Version.
-export MOODLE_DOCKER_PHP_VERSION=${MOODLE_DOCKER_PHP_VERSION:-7.2}
+export MOODLE_DOCKER_PHP_VERSION=${MOODLE_DOCKER_PHP_VERSION:-7.4}
 
 # Database flavour
 if [ "$MOODLE_DOCKER_DB" != 'pgsql' ];
@@ -44,7 +51,7 @@ if [ -f $filename ]; then
     dockercompose="${dockercompose} -f ${filename}"
 fi
 
-# Mobile app deprecated variables
+# Fix mobile app deprecated variables
 if [ ! -z "$MOODLE_APP_VERSION" ];
 then
     echo 'Warning: $MOODLE_APP_VERSION is deprecated, use $MOODLE_DOCKER_APP_VERSION instead'
@@ -55,20 +62,78 @@ then
     fi
 fi
 
+# Guess mobile app runtime
+if [ -z "$MOODLE_DOCKER_APP_RUNTIME" ];
+then
+    if [[ ! -z "$MOODLE_DOCKER_APP_PATH" ]];
+    then
+        appversion="$(cat $MOODLE_DOCKER_APP_PATH/package.json | grep -oP '"version": "\K\d\.\d\.\d{1,2}(-\w+)?(?=")')"
+    elif [[ ! -z "$MOODLE_DOCKER_APP_VERSION" ]];
+    then
+        appversion=$MOODLE_DOCKER_APP_VERSION
+    fi
+
+    if [[ ! -z $appversion ]];
+    then
+        if [[ ! -z "$(echo $appversion | grep -oP '\d\.\d\.\d{1,2}')" ]];
+        then
+            appmajorversion="$(echo $appversion | grep -oP '\d(?=\.\d\.\d{1,2})')"
+            appminorversion="$(echo $appversion | grep -oP '\d\.\K\d(?=\.\d{1,2})')"
+            apppatchversion="$(echo $appversion | grep -oP '\d\.\d\.\K\d{1,2}')"
+
+            if (( $appmajorversion > 3 ));
+            then
+                export MOODLE_DOCKER_APP_RUNTIME="ionic5"
+            elif (( $appminorversion != 9));
+            then
+                export MOODLE_DOCKER_APP_RUNTIME="ionic3"
+            elif (( $apppatchversion < 5 ));
+            then
+                export MOODLE_DOCKER_APP_RUNTIME="ionic3"
+            else
+                export MOODLE_DOCKER_APP_RUNTIME="ionic5"
+            fi
+        else
+            export MOODLE_DOCKER_APP_RUNTIME="ionic5"
+        fi
+    fi
+fi
+
 # Mobile app for development
 if [[ ! -z "$MOODLE_DOCKER_BROWSER" ]] && [[ "$MOODLE_DOCKER_BROWSER" == "chrome" ]] && [[ ! -z "$MOODLE_DOCKER_APP_PATH" ]];
 then
-    dockercompose="${dockercompose} -f ${basedir}/moodle-app-dev.yml"
+    dockercompose="${dockercompose} -f ${basedir}/moodle-app-dev-$MOODLE_DOCKER_APP_RUNTIME.yml"
+
 # Mobile app using a docker image
 elif [[ ! -z "$MOODLE_DOCKER_BROWSER" ]] && [[ "$MOODLE_DOCKER_BROWSER" == "chrome" ]] && [[ ! -z "$MOODLE_DOCKER_APP_VERSION" ]];
 then
-    dockercompose="${dockercompose} -f ${basedir}/moodle-app.yml"
+    dockercompose="${dockercompose} -f ${basedir}/moodle-app-$MOODLE_DOCKER_APP_RUNTIME.yml"
 fi
 
 # Selenium browser
-if [[ ! -z "$MOODLE_DOCKER_BROWSER" ]] && [[ "$MOODLE_DOCKER_BROWSER" != "firefox" ]];
+browserparts=(${MOODLE_DOCKER_BROWSER//:/ })
+export MOODLE_DOCKER_BROWSER_NAME=${browserparts[0]}
+export MOODLE_DOCKER_BROWSER_TAG=${browserparts[1]}
+
+if [[ -z "$MOODLE_DOCKER_BROWSER_NAME" ]];
 then
-    dockercompose="${dockercompose} -f ${basedir}/selenium.${MOODLE_DOCKER_BROWSER}.yml"
+    MOODLE_DOCKER_BROWSER_NAME=firefox
+fi
+
+if [[ -z "$MOODLE_DOCKER_BROWSER_TAG" ]];
+then
+    if [[ "$MOODLE_DOCKER_BROWSER_NAME" = "firefox" ]];
+    then
+        MOODLE_DOCKER_BROWSER_TAG=3
+    elif [[ "$MOODLE_DOCKER_BROWSER_NAME" = "chrome" ]];
+    then
+        MOODLE_DOCKER_BROWSER_TAG=3
+    fi
+fi
+
+if [[ "$MOODLE_DOCKER_BROWSER_NAME" != "firefox" ]];
+then
+    dockercompose="${dockercompose} -f ${basedir}/selenium.${MOODLE_DOCKER_BROWSER_NAME}.yml"
 fi
 
 # Selenium VNC port
@@ -88,6 +153,17 @@ fi
 if [[ ! -z "$MOODLE_DOCKER_PHPUNIT_EXTERNAL_SERVICES" ]];
 then
     dockercompose="${dockercompose} -f ${basedir}/phpunit-external-services.yml"
+fi
+
+#  Faildump directory
+if [[ ! -z "$MOODLE_DOCKER_BEHAT_FAILDUMP" ]];
+then
+    if [ ! -d "$MOODLE_DOCKER_BEHAT_FAILDUMP" ];
+    then
+        echo 'Error: $MOODLE_DOCKER_BEHAT_FAILDUMP is not an existing directory'
+        exit 1
+    fi
+    dockercompose="${dockercompose} -f ${basedir}/behat-faildump.yml"
 fi
 
 # Webserver host
