more elaborate cli command behat-test

diff --git a/behat-test b/behat-test
--- a/behat-test
+++ b/behat-test
@@ -1,77 +1,220 @@
 #!/usr/bin/env bash
 
-export MOODLE_DOCKER_WWWROOT=$1
+version=1.0
+
+#export MOODLE_DOCKER_WWWROOT=$1
 #export MOODLE_DOCKER_DB=mysql
 export MOODLE_DOCKER_DB=pgsql
 export MOODLE_DOCKER_SELENIUM_VNC_PORT=5900
 export MOODLE_DOCKER_PHP_VERSION=7.1
 
+# get options
+while getopts ":fhlnp:t:w:" x; do
+    case "${x}" in
+        f)
+            feature=1
+            ;;
+        h)
+            help=1
+            ;;
+        l)
+            list=1
+            ;;
+        n)
+            name=1
+            ;;
+        p)
+            parallels=${OPTARG}
+            ;;
+    	t)  
+            theme=${OPTARG}
+	       ;;
+    	w)  
+            webroot=${OPTARG}
+	       ;;
+        *)
+            usage
+            ;;
+    esac
+done
+shift $((OPTIND-1))
+
+
 usage() {
+	echo "ERROR! Missing parameter."
 	echo "usage: behat-test <path/to/moodlecode> [<tags>]"
 	exit 1
 }
 
-if [[ $1 == "" ]]
-then
-	usage
-fi
+help() {
+	echo "Usage: $0 something here...." 1>&2; 
+	echo
+	echo "available options:"
+	echo "-f: argument is a relative URI to a feature file to test"
+	echo "-h this help page"
+	echo "-n: argument is a name of a scenario to test"
+	echo "-p <parallels>: set number of parallel tests when initializing"
+	echo "-t <themename>: set theme for tests when initializing"
+	echo "-w <webroot>: set the path to the webroot directory to test"
+	echo
+	exit 1;
+}
 
-if [[ $2 == 'start' ]]
-then
-	echo "Starting testing environment"
+behat_up() {
+	rm -rf tmp
+	mkdir tmp
+
+	# Ask for the path to webroot if not already given as option
+	if [ -z ${webroot+x} ]; then
+		read -p "Enter the absolute path to webroot: " webroot
+		echo    # (optional) move to a new line
+	fi
+echo "writing txt"
+	echo $webroot > tmp/webroot.txt
+
+#	webroot=$(cat tmp/webroot.txt)
+	if [ ! -d $webroot ]; then
+		echo "webroot path does not exist - aborting...!"
+		exit 1
+	fi
+	export MOODLE_DOCKER_WWWROOT=$webroot
+
 	bin/moodle-docker-compose up -d
 	bin/moodle-docker-wait-for-db
+}
 
-	echo "==> You may now start a VNC client pointing at 0.0.0.0:5900 and enter the password 'secret'"
+get_webroot() {
+	if [ ! -f tmp/webroot.txt ]; then
+		read -p "Enter the absolute path to webroot: " webroot
+		echo    # (optional) move to a new line
+	else
+		webroot=$(cat tmp/webroot.txt)
+	fi
+	# and check it
+	if [ ! -d $webroot ]; then
+		echo "webroot path does not exist - aborting...!"
+		exit 1
+	fi
+	export MOODLE_DOCKER_WWWROOT=$webroot
+}
+
+behat_init() {
+	# get webroot
+	get_webroot
+
+	# parallels
+	if [ ! -z ${parallels+x} ]; then
+		echo $parallels > tmp/parallels.txt
+	else
+		rm -f tmp/parallels.txt
+	fi
+
+	# check for a theme option
+	if [ ! -z ${theme+x} ]; then
+		echo $theme > tmp/theme.txt
+	else
+		rm -f tmp/theme.txt
+	fi
 
 
-	echo "Initializing behat testing"
-	bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/init.php
-	echo "Behat testing up and ready for tests"
-	exit 1
-fi
+	if [ ! -z ${parallels+x} ]; then
+		if [ ! -z ${theme+x} ]; then
+			echo "Initializing behat testing for $parallels parallel runs with theme $theme"
+			bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/init.php --parallel=$parallels --add-core-features-to-theme="$theme"
+		else
+			echo "Initializing behat testing for $parallels parallel runs"
+			bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/init.php --parallel=$parallels
+		fi
+	else
+		echo "Initializing behat testing for a single run"
+		bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/init.php
+	fi
+}
 
-if [[ $2 == 'stop' ]]
-then 
+behat_stop() {
 	read -p "Do you really want to stop and remove the testing environment (y/N) " -n 1 -r
 	echo    # (optional) move to a new line
 	if [[ $REPLY =~ ^[Yy]$ ]]
 	then
 		echo "Bye..."
 		# Shut down and destroy containers
+		webroot=$(cat tmp/webroot.txt)
+		export MOODLE_DOCKER_WWWROOT=$webroot
 		bin/moodle-docker-compose down
-	    exit 1
+		rm -rf tmp
 	else
 		echo "Aborting..."
-		exit 1
 	fi
+	exit 1
+}
+
+list_scenarios() {
+	docker exec moodledocker_webserver_1 vendor/bin/behat --format=moodle_list --dry-run --config /var/www/behatdata/behatrun/behat/behat.yml --tags=@$1 > tmp/scenarios_raw
+	counter=0
+	while IFS= read -r line; do
+		((counter=$counter+1))
+		line=${line/html/moodle}
+		IFS=':' read -r -a array <<< "$line"
+		title=$(sed ${array[1]}'!d' ${array[0]})
+		echo "$counter: $line => ${title}"
+	done < tmp/scenarios_raw
+}
+
+if [ ! -z ${help+x} ]; then
+	help
 fi
 
-if [[ $2 == 'restart' ]]
-then 
-        read -p "Do you really want to stop and restart the testing environment (y/N) " -n 1 -r
-        echo    # (optional) move to a new line
-        if [[ $REPLY =~ ^[Yy]$ ]]
-        then
-                echo "Restarting the behat testing environment, please be patient..."
-                # Shut down and destroy containers
-                bin/moodle-docker-compose down
-		bin/moodle-docker-compose up -d
-	        bin/moodle-docker-wait-for-db
-	        echo "==> You may now start a VNC client pointing at 0.0.0.0:5900 and enter the password 'secret'"
-
-	        echo "Initializing behat testing"
-	        bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/init.php
-	        echo "Behat testing up and ready for tests"
-            exit 1
-        else
-                echo "Aborting..."
-                exit 1
-        fi
-fi
-
-if [[ $2 == "" ]]
+if [[ $1 == "?" ]]
 then
+	help
+fi
+
+if [[ $1 == "--help" ]]
+then
+	help
+fi
+
+if [[ $1 == "" ]]
+then
+	usage
+fi
+
+if [[ $1 == 'up' ]]
+then
+	echo "Bringing up testing environment"
+	behat_up
+	echo "==> Behat testing environment is up"
+	echo "==> You may now start a VNC client pointing at 0.0.0.0:5900 and enter the password 'secret'"
+	exit 1
+fi
+
+if [[ $1 == 'init' ]]
+then
+	echo "Initializing testing environment"
+	behat_init $3 $4
+	echo "==> Behat testing up and ready for tests"
+	exit 1
+fi
+
+if [[ $1 == 'start' ]]
+then
+	echo "Starting and initializing testing environment"
+	behat_up
+	behat_init $3 $4
+	echo "==> Behat testing up and ready for tests"
+	exit 1
+fi
+
+if [[ $1 == 'stop' ]]
+then 
+	behat_stop
+fi
+
+get_webroot
+
+# Run behat tests
+if [[ $1 == '' ]]; then
+	# No test specified - so running ALL tests?!
 	read -p "This will run for a VERY long time! Are you sure to test the complete system? (y/N) " -n 1 -r
 	echo    # (optional) move to a new line
 	if [[ ! $REPLY =~ ^[Yy]$ ]]
@@ -79,19 +222,27 @@ then
 		echo "Aborting..."
 	    exit 1
 	fi
-fi
-#echo "here we go..."
-
-# Run behat tests
-if [[ $2 == '' ]]
-then
+	# Indeed running all tests - this will run for hours!
 	bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/run.php
 else
-	if [[ $3 ==  '--rerun' ]]
-	then
-		bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/run.php --tags=@$2 --rerun
+	if [ ! -z ${feature+x} ]; then
+		echo "==> Testing single feature $1"
+		bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/run.php --feature=/var/www/html/$1
+	elif [ ! -z ${name+x} ]; then
+		echo "==> Testing single scenario $1"
+		bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/run.php --name="$1"
+	elif [ ! -z ${list+x} ]; then
+		echo "==> List of scenarios for $1"
+		list_scenarios $1
 	else
-		bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/run.php --tags=@$2
+		if [[ -f tmp/theme.txt ]]; then
+			theme=$(cat tmp/theme.txt)
+			echo "==> Testing plug in $1 with theme '$theme'"
+			bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/run.php --tags=@$1 --suite="$theme"
+		else
+			echo "==> Testing plug in $1"
+			bin/moodle-docker-compose exec webserver php admin/tool/behat/cli/run.php --tags=@$1
+		fi
 	fi
 fi
 
